{% set name = "libxsmm" %}
{% set version = "1.16.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hfp/{{ name }}/archive/{{ version }}.tar.gz
  sha256: bdc7554b56b9e0a380fc9c7b4f4394b41be863344858bc633bc9c25835c4c64e

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libxsmm', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - make
    - git
  host:
    - libblas
  run:

test:
  commands:
    - test -f $PREFIX/lib/libxsmmnoblas.so  # [linux]
    - test -f $PREFIX/lib/libxsmmgen.so  # [linux]
    - test -f $PREFIX/lib/libxsmmext.so  # [linux]
    - test -f $PREFIX/lib/libxsmmf.so  # [linux]
    - test -f $PREFIX/lib/libxsmm.so  # [linux]
    - test -f $PREFIX/lib/libxsmmnoblas.a  # [osx]
    - test -f $PREFIX/lib/libxsmmgen.a  # [osx]
    - test -f $PREFIX/lib/libxsmmext.a  # [osx]
    - test -f $PREFIX/lib/libxsmmf.a  # [osx]
    - test -f $PREFIX/lib/libxsmm.a  # [osx]

about:
  home: https://github.com/hfp/libxsmm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Library targeting Intel Architecture for specialized dense and sparse matrix operations, and deep learning primitives.

  description: |
    LIBXSMM is a library for specialized dense and sparse matrix operations 
    as well as for deep learning primitives such as small convolutions 
    targeting Intel Architecture.
  doc_url: https://libxsmm.readthedocs.io
  dev_url: https://github.com/hfp/libxsmm

extra:
  recipe-maintainers:
    - jan-janssen
    - hfp
