{% set name = "libxsmm" %}
{% set version = "1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hfp/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 9c0af4509ea341d1ee2c6c19fc6f19289318c3bd4b17844efeb9e7f9691abf76

build:
  number: 0
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage('libxsmm', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  host:
    - libblas
    - libcblas

test:
  commands:
    - conda inspect linkages {{ name }}  # [not win]
    - conda inspect objects {{ name }}  # [osx]
    - test -f $PREFIX/lib/libxsmmnoblas.so  # [linux]
    - test -f $PREFIX/lib/libxsmmgen.so  # [linux]
    - test -f $PREFIX/lib/libxsmmext.so  # [linux]
    - test -f $PREFIX/lib/libxsmmf.so  # [linux]
    - test -f $PREFIX/lib/libxsmm.so  # [linux]
    - test -f $PREFIX/lib/libxsmmnoblas.a  # [osx]
    - test -f $PREFIX/lib/libxsmmgen.a  # [osx]
    - test -f $PREFIX/lib/libxsmmext.a  # [osx]
    - test -f $PREFIX/lib/libxsmmf.a  # [osx]
    - test -f $PREFIX/lib/libxsmm.a  # [osx]

about:
  home: https://github.com/hfp/libxsmm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Library targeting Intel Architecture for specialized dense and sparse matrix operations, and deep learning primitives.'

  description: |
    LIBXSMM is a library for specialized dense and sparse matrix operations 
    as well as for deep learning primitives such as small convolutions 
    targeting Intel Architecture.
  doc_url: https://libxsmm.readthedocs.io
  dev_url: https://github.com/hfp/libxsmm

extra:
  recipe-maintainers:
    - jan-janssen
