travis:
  secure:
    BINSTAR_TOKEN: qWaapUGgNtV/O2irgZyoAC2rOQQ0kPgj7BCmODZSHA3lZm1kC/uA5bgaCERF8Ji/werHE9+8yO+duj62Wc4/gw5J7ZTKmChcOvYKSY+Vwf2CxfPccIjEKocK0CJR7BYhUrP1BPwjeYhSgCqJw8pxL780ZDZJQNCL13B/Zu12H/iQlmKVoZpgfJIOYNWIBkFwpcHOh2wDdwNzgyDwG/2n1wYiLNTdTfYs4pq6J1frSraG2C5mCF5/cIS26LsNB9ibJ3jZKN2211hui9MnqRHGUJLUBNAg7zTugim0kmJVKji+PTCNxug+Og/2TaaZ/vYHjydJ90DgkaYLpqFXNFKH/RCFoawzOVJxtTAEFrchZQX909+k2mUvQnS7zF05ZqXEEb++U3Wuo8DYJBFCq9pU12Uv86CZJZEnw5OkOfWeg/Ez5zYu3Dp3LHYQf3MpnPHO2pLA5H3kmNrxwC198aLUtrMJnuR13zUiwAmjOxUXp4HxicfIDbO8TgFYROpDsGWD9g39fIIDx0MxzYvk4MNmIa/7I6BPYyRLyLi2Ds6GFA+GlhpbWmDO7MANb/Ie1b6sdJ+PGb3KBoEketZTeyl1BRT7nGHnSnS5WlTOGNJgYEQ6zVmH8MrbBefkPLY+d4ysCEaXMh7vXiARr5jpnLcrhYGYeKAM+0xYC6DZ2XguV7w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
